# Generated by Django 4.0.2 on 2022-03-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='dateOfDepature',
            new_name='dateOfDeparture',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='ate',
            new_name='updateDate',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
